### ISSUE TITLE
net2ftp ok mais pas via le client FTP

### ISSUE THREAD

**Issue by LeOSW42** [maniackcrudelis/ftp_support_webapp_ynh#4]
Bonsoir,

Après une installation de ta version de la webapp, j'ai installé cette app. Un problème demeure :
La connexion via net2ftp marche parfaitement mais il m'est impossible de me connecter via mon client ftp (Filezilla), où j'ai cette erreur :

> Statut :	Échec de la tentative de connexion avec "ECONNREFUSED - Connexion refusée par le serveur".

Notons que mon app est sur domaine.tld/ et que net2ftp est à admin.domaine.tld/ftp_webapp_leo/
De plus par Filezilla j'essaye de me connecter sur domaine.tld et admin.domaine.tld mais même résultat.

Info complémentaire, en plus d'un utilisateur YunoHost nommé leo, j'ai aussi un utilisateur Linux (créé via `adduser`) du même nom.

Léo

**Comment by maniackcrudelis** [comment]
C'est là une erreur que j'avais déjà eu en utilisant l'app d'origine (https://github.com/Kloadut/my_webapp_ynh), je dois bien avouer que je n'ai pas retenter avec cette version de l'app car je n'ai pas de client ftp.

Il faut, je pense, se pencher sur la config de pure-ftpd pour trouver l'erreur.
https://github.com/maniackcrudelis/ftp_support_webapp_ynh/blob/master/scripts/install#L57-L63
Ça semble relativement simple, mais il faut que j'étudie cela.

**Comment by LeOSW42** [comment]
Je peux m'occuper de corriger ça dans les jours à venir, et je te
laisserais changer le paquet pour distribuer ce qu'il faut.

Léo

Le 17/01/2015 19:22, Maniack Crudelis a écrit :
>
> C'est là une erreur que j'avais déjà eu en utilisant l'app d'origine
> (https://github.com/Kloadut/my_webapp_ynh), je dois bien avouer que je
> n'ai pas retenter avec cette version de l'app car je n'ai pas de
> client ftp.
>
> Il faut, je pense, se pencher sur la config de pure-ftpd pour trouver
> l'erreur.
> https://github.com/maniackcrudelis/ftp_support_webapp_ynh/blob/master/scripts/install#L57-L63
> Ça semble relativement simple, mais il faut que j'étudie cela.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maniackcrudelis/ftp_support_webapp_ynh/issues/4#issuecomment-70377862>.
>

-- 
Léo SERRE
  06.18.62.32.05
  leo-serre.legtux.org

**Comment by maniackcrudelis** [comment]
Je prendrais ta contribution avec plaisir ;)

Toutefois, la vérité est ailleurs... Sur mon install ça fonctionne...
Je tenterais sur une machine virtuelle pour voir.

**Comment by LeOSW42** [comment]
Le problème chez moi est tout con, par défaut le port FTP est 21, or tu le configure sur 21021 :

https://github.com/maniackcrudelis/ftp_support_webapp_ynh/blob/master/scripts/install#L63

**Comment by maniackcrudelis** [comment]
Ah oui en effet, ce qui explique que ça a fonctionné lors de mon test.
C'est précisé sur l'index.html de la webapp toutefois.
https://github.com/maniackcrudelis/my_webapp_ynh/blob/master/sources/index_ftp.html#L8

L'idée est de ne pas interférer avec le véritable serveur ftp qui est en préparation pour yunohost
https://github.com/abeudin/proftpd_ynh/blob/master/conf/proftpd.conf#L41

En tout cas, c'est une bonne nouvelle que la connexion par un client externe soit fonctionnelle.
Je devrais peut-être trouver un endroit où repréciser qu'il faut utiliser le port 21021.

**Comment by LeOSW42** [comment]
C'est indiqué sur l'index de la webapp que si celle-ci est installée
après le support FTP.
Tu pourrais le mettre dans le manifest près de la description.

Léo

Le 18/01/2015 01:19, Maniack Crudelis a écrit :
>
> Ah oui en effet, ce qui explique que ça a fonctionné lors de mon test.
> C'est précisé sur l'index.html de la webapp toutefois.
> https://github.com/maniackcrudelis/my_webapp_ynh/blob/master/sources/index_ftp.html#L8
>
> L'idée est de ne pas interférer avec le véritable serveur ftp qui est
> en préparation pour yunohost
> https://github.com/abeudin/proftpd_ynh/blob/master/conf/proftpd.conf#L41
>
> En tout cas, c'est une bonne nouvelle que la connexion par un client
> externe soit fonctionnelle.
> Je devrais peut-être trouver un endroit où repréciser qu'il faut
> utiliser le port 21021.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/maniackcrudelis/ftp_support_webapp_ynh/issues/4#issuecomment-70390808>.
>

-- 
Léo SERRE
  06.18.62.32.05
  leo-serre.legtux.org

**Comment by maniackcrudelis** [comment]
C'est vrai, j'avais zappé ce point!
Je m'occupe de ça.
